// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWhuNwL3AaPICJXuzCve6En0Fmdldnewo',
    appId: '1:16323067957:web:9b717cc4370b47c032b17c',
    messagingSenderId: '16323067957',
    projectId: 'sehati-appmobile',
    authDomain: 'sehati-appmobile.firebaseapp.com',
    storageBucket: 'sehati-appmobile.firebasestorage.app',
    measurementId: 'G-Y137LFRHX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJEnks6J0XymRezvlXy_U7quYOCnlm7Kg',
    appId: '1:16323067957:android:d242894672ec256632b17c',
    messagingSenderId: '16323067957',
    projectId: 'sehati-appmobile',
    storageBucket: 'sehati-appmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlbD5M9clSR_ujZP51i3ypVlXPt2lGdM',
    appId: '1:16323067957:ios:2ff11a8a703e8ca532b17c',
    messagingSenderId: '16323067957',
    projectId: 'sehati-appmobile',
    storageBucket: 'sehati-appmobile.firebasestorage.app',
    iosBundleId: 'com.example.uasNaufalbimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlbD5M9clSR_ujZP51i3ypVlXPt2lGdM',
    appId: '1:16323067957:ios:2ff11a8a703e8ca532b17c',
    messagingSenderId: '16323067957',
    projectId: 'sehati-appmobile',
    storageBucket: 'sehati-appmobile.firebasestorage.app',
    iosBundleId: 'com.example.uasNaufalbimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWhuNwL3AaPICJXuzCve6En0Fmdldnewo',
    appId: '1:16323067957:web:78761e503220c08132b17c',
    messagingSenderId: '16323067957',
    projectId: 'sehati-appmobile',
    authDomain: 'sehati-appmobile.firebaseapp.com',
    storageBucket: 'sehati-appmobile.firebasestorage.app',
    measurementId: 'G-W20Z4HV3GH',
  );
}
